version: '3.1'

services:
  app:
    build:
      context: .
    image: armand1m/golinks:latest
    ports:
      - 3000:3000/tcp
    networks:
      - overlay
    environment:
      DATABASE_CONNECTION_STRING: postgres://dev:dev@db:5432/golinks
      DATABASE_SCHEMA: public
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: golinks
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    networks:
      - overlay
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/1-links-table.sql:/docker-entrypoint-initdb.d/1-links-table.sql
      - ./database/2-jwt-token-type.sql:/docker-entrypoint-initdb.d/2-jwt-token-type.sql
      - ./database/3-users-table.sql:/docker-entrypoint-initdb.d/3-users-table.sql
      - ./database/4-authenticate-function.sql:/docker-entrypoint-initdb.d/4-authenticate-function.sql
    ports:
      - 5432:5432/tcp
 
volumes:
  db-data:
    driver: local

networks:
  overlay: