version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: golinks
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - 5432:5432/tcp
 
volumes:
  db-data:
    driver: local