version: '3.1'

services:
  app:
    build:
      context: .
    image: armand1m/golinks:latest
    ports:
      - 3000:3000/tcp
    networks:
      - overlay
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: golinks
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    networks:
      - overlay
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/1-tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
      - ./database/2-roles.sql:/docker-entrypoint-initdb.d/2-roles.sql
      - ./database/3-functions.sql:/docker-entrypoint-initdb.d/3-functions.sql
      - ./database/4-policies.sql:/docker-entrypoint-initdb.d/4-policies.sql
    ports:
      - 5432:5432/tcp
 
volumes:
  db-data:
    driver: local

networks:
  overlay: